# Service to switch active pods to current ones
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer