# Crating pods with the image
apiVersion: v1
kind: ReplicationController
metadata:
  name: blue
spec:
  replicas: 1
  selector:
    app: blue
  template:
    metadata:
      name: blue
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: cabreu90/site:blue
        ports:
        - containerPort: 80